services:
  gis:
    container_name: gis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

# networks:
#   default:
#     external:
#       name: ghub-permission-lambda_default