
http:
  host: 'localhost'
  port: 8080

application:
  NODE_ENV: 'local'
  GIT_SHA: '131384ca7831e71d31fa306274a59c17a84462d6'
  jwt_expires_in: 1000
  jwt_secret: 'nYZgboJ1LXHL3EhjX64VFwkjq1WJ7bmxRTNavP7rd7NVLtd0hbBENC4crmYH4C7e'
  gms_default_scope: 'games:get games:create games:update games:delete'

database:
  mongo:
    username: <mongo_username>
    password: <mongo_password>
    name: <mongo_db_name>
    connection_string: <mongo_conn_str>

firebase:
  client_email: '<firebase_client_email>' 
  project_id: '<firebase_project_id>'
  private_key_id: '<firebase_private_key_id>'
